name: GitHub Prd Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-Reusable-Workflow-Prd:
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - run: echo "This is on ${{ vars.ENV_FULLNAME }} environment."
  call-reusable-workflow-prd:
    uses: ./.github/workflows/reusable.yml
    with:
      environment-var: prd