name: GitHub Reusable Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_call:
    inputs:
      environment-var:
        required: true
        type: string
jobs:
  Explore-GitHub-Reusable-Workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is on ${{ vars.ENV_FULLNAME }} environment."